name: E2E Test
on:
  push:
    branches:
      - main
  schedule:
    - cron: '7,37 * * * *' # Runs at 7 and 37 minutes past every hour
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Set up Chrome
        id: setup_chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
          install-chromedriver: true
      - name: Run Nightwatch e2e tests on Prod
        env:
          CHROME_BIN: ${{ steps.setup_chrome.outputs.chrome-path }}
        run: npx nightwatch nightwatch/e2e-test-of-uiucchat-prod.js
